version: '3.6'

services: 
    banco_topicos:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Pesquisa
            MYSQL_USER: user
            MYSQL_PASSWORD: user
    
        ports:
            - "3306:3306"


